// Copyright 2026 GSF-001
//
// Licensed under the ARCLUX MMO License v1 (GSF-001) — Source-available, No Commercial Game Clone.
// See LICENSE-MMO in the repo root. SPDX: LicenseRef-ARCLUX-MMO.
//

// planetary/qualityBudget.ts - 10.X.4 quality and budget policy.
// Distance plus volume cost selects one of four quality levels with graceful
// degradation; the budget decision gates expensive effects (particles, god
// rays, shadows). Deterministic jitter keeps handoff and reconnect stable.
// The persistence boundary declares which effects survive a region handoff
// and which the client regenerates. Pure logic: no rendering, no authority.

export type QualityLevel = "FAR" | "MEDIUM" | "NEAR" | "CINEMATIC";

export const QUALITY_COST: Record<QualityLevel, number> = {
  FAR: 0.15,
  MEDIUM: 0.35,
  NEAR: 0.65,
  CINEMATIC: 1.0,
};

const CINEMATIC_DIST = 80;
const NEAR_DIST = 300;
const MEDIUM_DIST = 1200;
const DOWNGRADE_COST = 0.3;
const SEVERE_DOWNGRADE_COST = 0.15;

export function deriveQualityLevel(distance: number, volumeCost: number): QualityLevel {
  const raw: QualityLevel =
    distance < CINEMATIC_DIST
      ? "CINEMATIC"
      : distance < NEAR_DIST
        ? "NEAR"
        : distance < MEDIUM_DIST
          ? "MEDIUM"
          : "FAR";
  if (volumeCost < DOWNGRADE_COST && raw === "CINEMATIC") return "NEAR";
  if (volumeCost < SEVERE_DOWNGRADE_COST && raw === "NEAR") return "MEDIUM";
  return raw;
}

/**
 * Stable variant that keeps the previous level inside a hysteresis band,
 * so borderline distances do not oscillate between levels each frame.
 */
export function deriveQualityLevelStable(
  distance: number,
  volumeCost: number,
  prev: QualityLevel,
): QualityLevel {
  const next = deriveQualityLevel(distance, volumeCost);
  const order: QualityLevel[] = ["FAR", "MEDIUM", "NEAR", "CINEMATIC"];
  const diff = order.indexOf(next) - order.indexOf(prev);
  if (Math.abs(diff) > 1) return next;
  if (diff === 1) {
    const margin =
      prev === "FAR" ? MEDIUM_DIST * 0.9 : prev === "MEDIUM" ? NEAR_DIST * 0.9 : CINEMATIC_DIST * 0.9;
    if (distance > margin) return prev;
  }
  if (diff === -1) {
    const margin =
      prev === "CINEMATIC" ? CINEMATIC_DIST * 1.1 : prev === "NEAR" ? NEAR_DIST * 1.1 : MEDIUM_DIST * 1.1;
    if (distance < margin) return prev;
  }
  return next;
}

export interface BudgetDecision {
  quality: QualityLevel;
  cost: number; // 0..1
  allowParticles: boolean;
  allowGodRays: boolean;
  allowShadows: boolean;
}

export function getBudget(distance: number, volumeCost: number, importance: number): BudgetDecision {
  const quality = deriveQualityLevel(distance, volumeCost);
  const cost = QUALITY_COST[quality] * (0.5 + importance * 0.5) * (0.3 + volumeCost * 0.7);
  return {
    quality,
    cost: Math.min(1, cost),
    allowParticles: quality !== "FAR",
    allowGodRays: quality === "CINEMATIC" || quality === "NEAR",
    allowShadows: quality !== "FAR",
  };
}

export function shouldAllowEffect(decision: BudgetDecision, effect: string): boolean {
  if (effect === "godRays") return decision.allowGodRays;
  if (effect === "particles") return decision.allowParticles;
  if (effect === "shadows") return decision.allowShadows;
  return decision.cost < 0.6;
}

export function adaptQualityForFps(current: QualityLevel, fps: number): QualityLevel {
  if (fps < 28 && current === "CINEMATIC") return "NEAR";
  if (fps < 24 && current === "NEAR") return "MEDIUM";
  if (fps < 20) return "FAR";
  if (fps > 55 && current === "FAR") return "MEDIUM";
  return current;
}

/** Deterministic 0..1 jitter from seed, tick quantum, chunk, and cell. */
export function deterministicJitter(
  planetSeed: number,
  tick: number,
  chunkKey: string,
  pos: { x: number; z: number },
): number {
  let h = 2166136261;
  const s = `${planetSeed}:${chunkKey}:${Math.floor(tick / 30)}:${Math.floor(pos.x / 100)}:${Math.floor(pos.z / 100)}`;
  for (let i = 0; i < s.length; i++) h = Math.imul(h ^ s.charCodeAt(i), 16777619);
  return (h >>> 0) / 4294967296;
}

const PERSISTENT_EFFECTS = new Set(["weather", "facility", "terrain", "vessel", "facilityState", "chunk"]);
const TRANSIENT_EFFECTS = new Set(["particles", "godRays", "fog", "splash", "flash", "spray", "dust"]);

/**
 * Persistence boundary: persistent effects survive handoff and reconnect,
 * transient effects are regenerated by the client.
 */
export function isPersistent(effect: string): boolean {
  if (PERSISTENT_EFFECTS.has(effect)) return true;
  if (TRANSIENT_EFFECTS.has(effect)) return false;
  for (const p of PERSISTENT_EFFECTS) if (effect.startsWith(p)) return true;
  for (const t of TRANSIENT_EFFECTS) if (effect.startsWith(t)) return false;
  return false;
}

/** Effects the client must regenerate after handoff or reconnect. */
export function getTransientEffects(): string[] {
  return ["particles", "godRays", "fog", "splash", "flash", "spray"];
}
