/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mapSidebar: [
    {
      type: 'category',
      label: 'Intelligence',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'intelligence' }],
    },
    {
      type: 'category',
      label: 'Platform',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'platform' }],
    },
    {
      type: 'category',
      label: 'Apps',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'apps' }],
    },
  ],
};

module.exports = sidebars;
