; UE5 DefaultEngine.ini — Slice 0 (00-migrasi.md §2).
; DX12/SM6 + TSR + VSM + World Partition (streaming CLIENT saja, otoritas tetap server).

[/Script/Engine.RendererSettings]
r.ReflectionMethod=1
r.GenerateMeshDistanceFields=True
r.DynamicGlobalIlluminationMethod=1
r.Shadow.Virtual.Enable=1
r.AntiAliasingMethod=4

[/Script/Engine.Engine]
bUseWorldPartition=True

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
DefaultGraphicsRHI=DefaultGraphicsRHI_DX12
-D3D11=False
+D3D12=True
