#!/usr/bin/env node
/**
 * ARCLUX Docs — content generator (v2: MDX-safe + link-fix)
 * Baca file sumber asli di root repo, tulis ulang jadi halaman docs-site/docs/*.md
 * Jalankan ulang kapan pun repo berubah: node scripts/generate-docs.js
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const DOCS_OUT = path.join(ROOT, 'docs-site', 'docs');
const GITHUB_BASE = 'https://github.com/GSF-001/ARCLUX/blob/main/';

function readIfExists(relPath) {
  const p = path.join(ROOT, relPath);
  if (fs.existsSync(p)) return fs.readFileSync(p, 'utf-8');
  return null;
}

function stripFrontmatter(content) {
  return content.replace(/^---[\s\S]*?---\n/, '');
}

// Escape teks placeholder <kayak-ini> yang bukan URL/autolink, biar gak dianggap tag JSX oleh MDX.
// Fenced code block (```) dilewati karena isinya sudah aman dari parser JSX.
function mdxSafe(text) {
  const fenceBlocks = [];
  let out = text.replace(/```[\s\S]*?```/g, (m) => {
    fenceBlocks.push(m);
    return `\u0000FENCE${fenceBlocks.length - 1}\u0000`;
  });

  const autolinks = [];
  out = out.replace(/<(https?:\/\/[^\s<>]+|mailto:[^\s<>]+)>/g, (m) => {
    autolinks.push(m);
    return `\u0000AUTOLINK${autolinks.length - 1}\u0000`;
  });

  out = out.replace(/<!--/g, '\u0000CMTOPEN\u0000').replace(/-->/g, '\u0000CMTCLOSE\u0000');

  // Bulldozer: sisa "<" apapun di luar fence/autolink/comment, escape jadi entity.
  // Ini gak butuh hitung buka-tutup tag -- pasti gak akan lagi dibaca sebagai JSX.
  out = out.replace(/</g, '&lt;');

  out = out.replace(/\u0000CMTOPEN\u0000/g, '<!--').replace(/\u0000CMTCLOSE\u0000/g, '-->');
  out = out.replace(/\u0000AUTOLINK(\d+)\u0000/g, (m, i) => autolinks[Number(i)]);
  out = out.replace(/\u0000FENCE(\d+)\u0000/g, (m, i) => fenceBlocks[Number(i)]);

  return out;
}

// Ganti link relatif ke file .md (yang lokasinya di root repo, bukan di docs-site/docs)
// jadi link langsung ke GitHub, biar gak "broken link".
function fixLinks(text) {
  return text.replace(/\]\((?!https?:\/\/)([^)\s]+\.md[^)\s]*)\)/g, (match, p1) => {
    const clean = p1.replace(/^\.?\//, '');
    return `](${GITHUB_BASE}${clean})`;
  });
}

function sanitize(text) {
  return fixLinks(mdxSafe(text));
}

function writeDoc(filename, title, sidebarPosition, body) {
  const frontmatter = `---\ntitle: ${title}\nsidebar_position: ${sidebarPosition}\n---\n\n`;
  const note = `<!-- Auto-generated by scripts/generate-docs.js dari file sumber repo. Edit sumbernya, lalu jalankan generator ulang. -->\n\n`;
  const safeBody = sanitize(body.trim());
  fs.writeFileSync(path.join(DOCS_OUT, filename), frontmatter + note + safeBody + '\n');
  console.log(`  ok ${filename}`);
}

function extractSection(content, headingRegex) {
  if (!content) return null;
  const lines = content.split('\n');
  const startIdx = lines.findIndex((l) => headingRegex.test(l));
  if (startIdx === -1) return null;
  let endIdx = lines.length;
  const headingLevel = (lines[startIdx].match(/^#+/) || ['#'])[0].length;
  for (let i = startIdx + 1; i < lines.length; i++) {
    const m = lines[i].match(/^(#+)\s/);
    if (m && m[1].length <= headingLevel) {
      endIdx = i;
      break;
    }
  }
  return lines.slice(startIdx, endIdx).join('\n').trim();
}

console.log('== ARCLUX Docs -- generating content from repo ==\n');

if (!fs.existsSync(DOCS_OUT)) {
  console.error('ERROR: docs-site/docs belum ada. Jalankan 01-scaffold-docusaurus.sh dulu.');
  process.exit(1);
}

const readme = readIfExists('README.md');
const context = readIfExists('CONTEXT.md');

{
  let body = '';
  if (readme) {
    const cut = readme.search(/^#+\s*(Installation|Usage|Getting Started|Quickstart)/im);
    body += stripFrontmatter(cut > -1 ? readme.slice(0, cut) : readme);
  }
  if (context) body += `\n\n## Context tambahan\n\n${stripFrontmatter(context)}`;
  if (!body.trim()) body = '_README.md tidak ditemukan di root repo._';
  writeDoc('intro.md', 'Intro', 1, body);
}

{
  let body = '';
  const quickstart = readIfExists('QUICKSTART.md');
  if (quickstart) body += stripFrontmatter(quickstart);
  if (readme) {
    const installSection = extractSection(readme, /^#+\s*(Installation|Getting Started)/im);
    const usageSection = extractSection(readme, /^#+\s*(Usage|CLI|Commands)/im);
    if (installSection) body += `\n\n${installSection}`;
    if (usageSection) body += `\n\n${usageSection}`;
  }
  if (!body.trim()) body = '_Tidak ditemukan bagian instalasi/usage di README.md atau QUICKSTART.md._';
  writeDoc('usage.md', 'Instalasi & Penggunaan', 2, body);
}

{
  const arch = readIfExists('ARCHITECTURE_MAP.md');
  const body = arch ? stripFrontmatter(arch) : '_ARCHITECTURE_MAP.md tidak ditemukan di root repo._';
  writeDoc('architecture.md', 'Arsitektur', 3, body);
}

{
  let body = '';
  const tooling = readIfExists('TOOLING.md');
  if (tooling) body += stripFrontmatter(tooling);
  const pkgJson = readIfExists('package.json');
  if (pkgJson) {
    try {
      const pkg = JSON.parse(pkgJson);
      if (pkg.workspaces) {
        body += `\n\n## Workspaces\n\n`;
        const ws = Array.isArray(pkg.workspaces) ? pkg.workspaces : pkg.workspaces.packages || [];
        ws.forEach((w) => (body += `- \`${w}\`\n`));
      }
    } catch (e) {}
  }
  if (!body.trim()) body = '_TOOLING.md tidak ditemukan._';
  writeDoc('stack.md', 'Stack & Environment', 4, body);
}

{
  const progres = readIfExists('PROGRES.md');
  const body = progres ? stripFrontmatter(progres) : '_PROGRES.md tidak ditemukan di root repo._';
  writeDoc('status.md', 'Status & Progress', 5, body);
}

{
  let body = '';
  if (context) {
    const gotchaSection = extractSection(context, /^#+\s*(Gotchas|Known Issues|Catatan)/im);
    if (gotchaSection) body += gotchaSection;
  }
  if (!body.trim()) {
    body =
      '_Belum ada bagian "Gotchas"/"Known Issues" terdeteksi otomatis di CONTEXT.md. ' +
      'Tambahkan section dengan heading `## Gotchas` di CONTEXT.md, atau edit file ini manual._';
  }
  writeDoc('gotchas.md', 'Gotchas', 6, body);
}

console.log('\n== Selesai. Halaman ke-generate ke docs-site/docs/ ==');
